### ISSUE TITLE
Duplicate jQuery is loaded over HTTP (not HTTPS)

### ISSUE THREAD

**Issue by joker314** [PianoBin/PianoBin.github.io#13]
It looks like there are a few slight issues with the [loading of jQuery](https://github.com/PianoBin/PianoBin.github.io/blob/master/index.html#L260).

- It appears this is the second time jQuery is loaded, since there exists [a first time](https://github.com/PianoBin/PianoBin.github.io/blob/master/index.html#L260).
- The jQuery is loaded over the HTTP protocol, but the rest of the site is loaded over HTTPS. For security reasons, modern browsers will not allow the main page to read the contents of the JavaScript unless it is loaded under HTTPS too -- if you can hijack the JavaScript, you can hijack the page. (Note that this jQuery host supports, but does not mandate, HTTPS)

Since the browser blocks the request (or at the very least the response), and since jQuery has already been loaded, perhaps it would be best to remove the second request for jQuery. If it's needed, then perhaps it would be best to correct it to use an HTTPS schema?

Cool site btw 👍

**Comment by PianoBin** [comment]
Thanks for the heads up!
